StylesPath = _vale
MinAlertLevel = warning
IgnoredScopes = text.frontmatter, code, tt, b, strong, i, a

# 1. Полностью отключаем проверку автогенерируемого справочника и релиз-ноутсов
[content/reference/**]
BasedOnStyles = 

[{content/manuals/*/release-notes.md,content/manuals/*/release-notes/**,content/manuals/**/release-notes.md,content/manuals/desktop/previous-versions/**}]
BasedOnStyles = 

# 2. Правила для всех остальных Markdown-файлов
[*.md]
BasedOnStyles = Docker, Vale
TokenIgnores = ({{[^}]+}}\S*)
BlockIgnores = (?m)^[ \t]*({{[^}]+}})[ \t]*$, (\[[^\]]*{{[^}]+}}[^\]]*\]\([^)]*\)), ({{<\s*file\s[^>]*>}}[\s\S]*?{{<\s*/\s*file\s*>}})

# 3. Полностью отключаем словари и проверку терминов/спеллинга
Vale.Spelling = NO
Vale.Terms = NO
Docker.Capitalization = NO

# 4. Отключаем шумные стилистические правила
Docker.Exclamation = NO
Docker.RecommendedWords = NO
Docker.We = NO
Docker.Avoid = NO
Docker.Spacing = NO