StylesPath = _vale
MinAlertLevel = warning
IgnoredScopes = text.frontmatter, code, tt, b, strong, i, a

# 1. Полностью отключаем проверку автогенерируемого справочника и релиз-ноутсов
[content/reference/**]
BasedOnStyles = 

[{content/manuals/*/release-notes.md,content/manuals/*/release-notes/**,content/manuals/**/release-notes.md,content/manuals/desktop/previous-versions/**}]
BasedOnStyles = 

# 2. Правила для всех остальных Markdown-файлов (Все правила ВКЛЮЧЕНЫ, кроме Spelling)
[*.md]
BasedOnStyles = Docker
Vale.Spelling = NO
Docker.Spelling = NO
Docker.Vale.Spelling = NO
TokenIgnores = ({{[^}]+}}\S*)
BlockIgnores = (?m)^[ \t]*({{[^}]+}})[ \t]*$, (\[[^\]]*{{[^}]+}}[^\]]*\]\([^)]*\)), ({{<\s*file\s[^>]*>}}[\s\S]*?{{<\s*/\s*file\s*>}})й