name: Deploy Hugo Docs to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Позволяет запускать сборку вручную из интерфейса GitHub

# Права доступа, необходимые для деплоя на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Отменяем старые параллельные сборки, если запущен новый пуш
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Скачиваем субмодули, если они используются
          fetch-depth: 0

      # Автоматически определяет baseURL с учетом имени вашего репозитория
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # Устанавливаем Hugo Extended (extended: true критичен для компиляции SCSS/SASS стилей Docker)
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Собираем статику
      - name: Build Hugo Site
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      # Передаем папку /public экшену деплоя
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4